import java.awt.Color;
import javax.swing.JOptionPane;

/**
 * A simple login application with a GUI.
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login.
     */
    public login() {
        initComponents();
        jLabel2.setVisible(false); // Hide the error message initially
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, 30));

        jLabel1.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 48)); // NOI18N
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jLabel2.setText("Incorrect username and password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, -1, -1));

        jTextField1.setFont(new java.awt.Font("Montserrat Medium", 2, 12)); // NOI18N
        jTextField1.setText("enter username");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, 156, -1));

        jPasswordField1.setFont(new java.awt.Font("Montserrat Medium", 2, 12)); // NOI18N
        jPasswordField1.setText("Enter password");
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 156, -1));

        jButton2.setFont(new java.awt.Font("Montserrat Medium", 2, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, 101, -1));

        jCheckBox1.setFont(new java.awt.Font("Montserrat Medium", 2, 12)); // NOI18N
        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(this::jCheckBox1ActionPerformed);
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 390, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login background.PNG"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, -1, -1));

        pack();
    }

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {
        jLabel2.setVisible(false); // Hide the error message
        if (jTextField1.getText().equals("enter username")) {
            jTextField1.setText(""); // Clear the default text
            jTextField1.setForeground(new Color(0, 118, 221)); // Set text color
        }
    }

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {
        if (jTextField1.getText().trim().isEmpty()) {
            jTextField1.setText("enter username"); // Reset default text
            jTextField1.setForeground(new Color(150, 150, 150)); // Set placeholder color
        }
    }

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {
        jLabel2.setVisible(false); // Hide the error message
        if (new String(jPasswordField1.getPassword()).equals("Enter password")) {
            jPasswordField1.setText(""); // Clear the default text
            jPasswordField1.setForeground(new Color(0, 118, 221)); // Set text color
        }
    }

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {
        if (jPasswordField1.getPassword().length == 0) {
            jPasswordField1.setText("Enter password"); // Reset default text
            jPasswordField1.setForeground(new Color(150, 150, 150)); // Set placeholder color
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to exit the application?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0); // Exit the application
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        String username = jTextField1.getText();
        String password = new String(jPasswordField1.getPassword());

        if (username.equals("gmp") && password.equals("admin")) {
            this.setVisible(false); // Hide the login window
            new home().setVisible(true); // Open the home window
        } else {
            jLabel2.setVisible(true); // Show error message
        }
    }

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {
        if (jCheckBox1.isSelected()) {
            jPasswordField1.setEchoChar((char) 0); // Show password
        } else {
            jPasswordField1.setEchoChar('*'); // Hide password
        }
    }

    /**
     * Main method to launch the application.
     */
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> {
            new login().setVisible(true); // Display the login window
        });
    }

    // Variables declaration
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
}
